name: LOCI Analysis
on:
  push:
    branches:
      - main*
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  loci:
    runs-on: ubuntu-24.04-arm

    env:
      LOCI_PROJECT: zed
      LOCI_API_KEY: '${{ secrets.LOCI_API_KEY }}'
      LOCI_BACKEND_URL: '${{ vars.LOCI_BACKEND_URL }}'

    environment: ${{ vars.LOCI_ENV || 'PROD__AL_DEMO' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: ./script/linux

      - name: Install Rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Build
        run: |
          cargo build --package zed --package cli --package remote_server
          ls target/*
        
      - name: Upload
        uses: auroralabs-loci/loci-action@v1
        with:
          mode: upload
          binaries: |
                target/debug/zed
                target/debug/cli
                target/debug/remote_server
          project: '${{ env.LOCI_PROJECT }}'
          wait-base: 'true'
